set number
set relativenumber
set autoindent
set background=dark
set ruler
set laststatus=2
set tabstop=4
set linebreak
set visualbell
set title
set smarttab    
set cursorline
set jumpoptions="stack,view"
set mouse=a
set mouse=nicr
