return {
  { 'ficcdaf/ashen.nvim' },
  { 'ellisonleao/gruvbox.nvim' },
  { 'tiagovla/tokyodark.nvim' },
  { 'rebelot/kanagawa.nvim' },
  { 'rose-pine/neovim', name = 'rose-pine' },
  { 'scottmckendry/cyberdream.nvim' },
  { 'comfysage/evergarden' },
  { 'zootedb0t/citruszest.nvim' },
  { 'catppuccin/nvim', name = 'catppuccin' },
  { 'dgox16/oldworld.nvim' },
  { 'Mofiqul/dracula.nvim' },
  { 'craftzdog/solarized-osaka.nvim' },
  { 'ellisonleao/gruvbox.nvim' },
  { 'blazkowolf/gruber-darker.nvim' },
  { 'mellow-theme/mellow.nvim' },
  { 'HoNamDuong/hybrid.nvim' },
  { 'tanvirtin/monokai.nvim' },
  { 'EdenEast/nightfox.nvim' },
  { 'Mofiqul/vscode.nvim' },
  { 'navarasu/onedark.nvim' },
}
